import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import { WiStars } from "react-icons/wi";
import { StarryBg } from "../ui/StaryyBg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="customTheme" lang="en">
      <body>
        <StarryBg>
          <Nav />
          {children}
        </StarryBg>
      </body>
    </html>
  );
}
const Nav = async () => {
  const pages = await getPages();

  return (
    <nav className="relative z-20 flex items-center after:absolute after:bottom-4 after:h-[1px] after:w-11/12 after:bg-primary after:ml-auto after:left-0 after:right-0">
      <div className="text-neutral animate-pulse ease-in-out duration-200">
        <WiStars size={100} />
      </div>
      <h2 className="mr-auto text-neutral font-sans">Souza-dev.com</h2>
      <div className="mr-5 font-display font-thin text-neutral uppercase text-sm">
        {pages.map((item: any, i: number) => {
          return (
            <>
              <Link className={`link link-hover `} href={"/"}>
                {item.title}
              </Link>
              {i === 0 && ","}
            </>
          );
        })}
      </div>
    </nav>
  );
};
